package windev

/*
这些宏定义来自winuser.h
只摘了一部分过来, 有兴趣的朋友可以查看头文件
*/

// 鼠标事件集合
const MOUSEEVENTF_MOVE = 0x0001       /* mouse move */
const MOUSEEVENTF_LEFTDOWN = 0x0002   /* left button down */
const MOUSEEVENTF_LEFTUP = 0x0004     /* left button up */
const MOUSEEVENTF_RIGHTDOWN = 0x0008  /* right button down */
const MOUSEEVENTF_RIGHTUP = 0x0010    /* right button up */
const MOUSEEVENTF_MIDDLEDOWN = 0x0020 /* middle button down */
const MOUSEEVENTF_MIDDLEUP = 0x0040   /* middle button up */
const MOUSEEVENTF_XDOWN = 0x0080      /* x button down */
const MOUSEEVENTF_XUP = 0x0100        /* x button down */
const MOUSEEVENTF_WHEEL = 0x0800      /* wheel button rolled */

// 键盘事件集合
const VK_LBUTTON = 0x01    // 鼠标左键
const VK_RBUTTON = 0x02    // 鼠标右键
const VK_MBUTTON = 0x04    // 鼠标中键
const VK_BACK = 0x08       // BackSpace
const VK_TAB = 0x09        // Tab
const VK_CLEAR = 0x0C      // Num Lock关闭时的数字区 5
const VK_RETURN = 0x0D     // Enter
const VK_SHIFT = 0x10      // Shift/左右shift都可以
const VK_CONTROL = 0x11    // Ctrl/左右Ctrl都可以
const VK_MENU = 0x12       // Alt/左右Alt都可以
const VK_PAUSE = 0x13      /* Pause*/
const VK_CAPITAL = 0x14    // Caps Lock
const VK_ESCAPE = 0x1B     // Esc
const VK_SPACE = 0x20      // Space
const VK_PRIOR = 0x21      // PgUp
const VK_NEXT = 0x22       // PgDn
const VK_END = 0x23        // End
const VK_HOME = 0x24       // Home
const VK_LEFT = 0x25       // 方向左
const VK_UP = 0x26         // 方向上
const VK_RIGHT = 0x27      // 方向右
const VK_DOWN = 0x28       // 方向下
const VK_SELECT = 0x29     /* Select*/
const VK_PRINT = 0x2A      /* Print*/
const VK_EXECUTE = 0x2B    /* Execute*/
const VK_SNAPSHOT = 0x2C   /* Print Screen键(抓屏)*/
const VK_INSERT = 0x2D     // Insert
const VK_DELETE = 0x2E     // Delete
const VK_HELP = 0x2F       /* Help*/
const VK_CHAR0 = 0x30      // '0'
const VK_CHAR1 = 0x31      // '1'
const VK_CHAR2 = 0x32      // '2'
const VK_CHAR3 = 0x33      // '3'
const VK_CHAR4 = 0x34      // '4'
const VK_CHAR5 = 0x35      // '5'
const VK_CHAR6 = 0x36      // '6'
const VK_CHAR7 = 0x37      // '7'
const VK_CHAR8 = 0x38      // '8'
const VK_CHAR9 = 0x39      // '9'
const VK_CHARA = 0x41      // 'A'
const VK_CHARB = 0x42      // 'B'
const VK_CHARC = 0x43      // 'C'
const VK_CHARD = 0x44      // 'D'
const VK_CHARE = 0x45      // 'E'
const VK_CHARF = 0x46      // 'F'
const VK_CHARG = 0x47      // 'G'
const VK_CHARH = 0x48      // 'H'
const VK_CHARI = 0x49      // 'I'
const VK_CHARJ = 0x4A      // 'J'
const VK_CHARK = 0x4B      // 'K'
const VK_CHARL = 0x4C      // 'L'
const VK_CHARM = 0x4D      // 'M'
const VK_CHARN = 0x4E      // 'N'
const VK_CHARO = 0x4F      // 'O'
const VK_CHARP = 0x50      // 'P'
const VK_CHARQ = 0x51      // 'Q'
const VK_CHARR = 0x52      // 'R'
const VK_CHARS = 0x53      // 'S'
const VK_CHART = 0x54      // 'T'
const VK_CHARU = 0x55      // 'U'
const VK_CHARV = 0x56      // 'V'
const VK_CHARW = 0x57      // 'W'
const VK_CHARX = 0x58      // 'X'
const VK_CHARY = 0x59      // 'Y'
const VK_CHARZ = 0x5A      // 'Z'
const VK_LWIN = 0x5B       // 左win键
const VK_RWIN = 0x5C       // 右win键
const VK_NUMPAD0 = 0x60    // 数字区 0
const VK_NUMPAD1 = 0x61    // 数字区 1
const VK_NUMPAD2 = 0x62    // 数字区 2
const VK_NUMPAD3 = 0x63    // 数字区 3
const VK_NUMPAD4 = 0x64    // 数字区 4
const VK_NUMPAD5 = 0x65    // 数字区 5
const VK_NUMPAD6 = 0x66    // 数字区 6
const VK_NUMPAD7 = 0x67    // 数字区 7
const VK_NUMPAD8 = 0x68    // 数字区 8
const VK_NUMPAD9 = 0x69    // 数字区 9
const VK_MULTIPLY = 0x6A   // 数字区 *
const VK_ADD = 0x6B        // 数字区 +
const VK_SEPARATOR = 0x6C  /* Sepatator*/
const VK_SUBTRACT = 0x6D   // 数字区 -
const VK_DECIMAL = 0x6E    // 数字区 小数点
const VK_DIVIDE = 0x6F     // 数字区 /
const VK_F1 = 0x70         // F1
const VK_F2 = 0x71         // F2
const VK_F3 = 0x72         // F3
const VK_F4 = 0x73         // F4
const VK_F5 = 0x74         // F5
const VK_F6 = 0x75         // F6
const VK_F7 = 0x76         // F7
const VK_F8 = 0x77         // F8
const VK_F9 = 0x78         // F9
const VK_F10 = 0x79        // F10
const VK_F11 = 0x7A        // F11
const VK_F12 = 0x7B        // F12
const VK_F13 = 0x7C        // F13
const VK_F14 = 0x7D        // F14
const VK_F15 = 0x7E        // F15
const VK_F16 = 0x7F        // F16
const VK_F17 = 0x80        // F17
const VK_F18 = 0x81        // F18
const VK_F19 = 0x82        // F19
const VK_F20 = 0x83        // F20
const VK_F21 = 0x84        // F21
const VK_F22 = 0x85        // F22
const VK_F23 = 0x86        // F23
const VK_F24 = 0x87        // F24
const VK_NUMLOCK = 0x90    // Num Lock
const VK_SCROLL = 0x91     /* Scroll Lock*/
const VK_LSHIFT = 0xA0     // 左shift
const VK_RSHIFT = 0xA1     // 右shift
const VK_LCONTROL = 0xA2   // 左Ctrl
const VK_RCONTROL = 0xA3   // 右Ctrl
const VK_LMENU = 0xA4      // 左Alt
const VK_RMENU = 0xA5      // 右Alt
const VK_OEM_1 = 0xBA      // ';:'
const VK_OEM_PLUS = 0xBB   // '=+'
const VK_OEM_COMMA = 0xBC  // ',<'
const VK_OEM_MINUS = 0xBD  // '-_'
const VK_OEM_PERIOD = 0xBE // '.>'
const VK_OEM_2 = 0xBF      // '/?'
const VK_OEM_3 = 0xC0      // '`~'
const VK_OEM_4 = 0xDB      // '[{'
const VK_OEM_5 = 0xDC      // '\|'
const VK_OEM_6 = 0xDD      // ']}'
const VK_OEM_7 = 0xDE      // ''"'
